sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tanmay14/docker-react -f Dockerfile.dev .

script:
  - docker run tanmay14/docker-react npm run test -- --coverage